version: 1.4.2.{build}

os: Previous Visual Studio 2015 RC

configuration: Release

install:

- ps: git submodule -q update --init

before_build:

- ps: >-

    nuget restore



    $vsixPath = "$env:appveyor_build_folder\source.extension.vsixmanifest"





    $manifestXml = New-Object XML



    $manifestXml.Load($vsixPath)



    $manifestXml.PackageManifest.Metadata.Identity.Version = $env:appveyor_build_version)



    $manifestXml.save($vsixPath)

build:

  project: BasicSccProvider.sln

  verbosity: minimal

test: off

artifacts:

- path: GitSccProvider\bin\Release\GitSccProvider.vsix

  name: GitSccProvider
