-
  os: Previous Visual Studio 2015 RC
  configuration: Release
  skip_tags: true
  branches:
    only:
      - dev
  
  
  environment:
    majorVersion: 1
    minorVersion: 5
    patchVersion: 0
    access_token:
      secure: D9+WTOpCzI8qcrBNULSrWHJeR4thDu4jxQmY/oHux1CYpAjfk2rrpShn8loWHGQc
    relName : GSCP-Dev-v%majorVersion%.%minorVersion%
    
    
  version: $(majorVersion).$(minorVersion).$(patchVersion).{build}


  install:

  - ps: >-

      (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

  before_build:
  - ps: >-
      $vsixPath = "$env:appveyor_build_folder\GitSccProvider\source.extension.vsixmanifest"
          $manifestXml = New-Object XML
          $manifestXml.Load($vsixPath)
          $manifestXml.PackageManifest.Metadata.Identity.Version = $env:appveyor_build_version
          $manifestXml.save($vsixPath)
  build_script:
    - nuget restore -Verbosity quiet
    - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

  test: off

  artifacts:

  - path: GitSccProvider\bin\Release\GitSccProvider.vsix

    name: GitSccProvider


  deploy:
    release: GSCP-Dev-v$(majorVersion).$(minorVersion)
    description: GSCP CI Build
    provider: GitHub
    auth_token: $(access_token) # your encrypted token from GitHub
    artifact: GitSccProvider\bin\Release\GitSccProvider.vsix           # upload all NuGet packages to release assets
    draft: false
    prerelease: true
  
  after_deploy:
  echo %relName%
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "build.server@appveyor.com"
  - git config --global user.name "Build Server"
  - git tag -a "relName" "%APPVEYOR_REPO_COMMIT%" -f
  - git push origin :/refs/tags/GSCP Dev-v%$env:majorVersion.$env:minorVersion -f