-
  os: Previous Visual Studio 2015 RC
  configuration: Release
  skip_tags: true
  
  branches:
    only:
      - master

  version: 1.5.0.{build}

  install:

  - ps: >-

      (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

  before_build:
    - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

  build_script:
    - nuget restore -Verbosity quiet
    - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  test: off
  artifacts:
  - path: GitSccProvider\bin\Release\GitSccProvider.vsix
    name: GitSccProvider


