version: 1.4.2.{build}
os: Visual Studio 2015

install:

- ps: >-

    (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex





    git submodule -q update --init


before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
test: off
artifacts:
- path: GitSccProvider\bin\Release\GitSccProvider.vsix
  name: GitSccProvider
